# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: youfu's Notes
author: 有福
description: 好好活着
avatar: http://7teb9r.com1.z0.glb.clouddn.com/20150401010521176.jpg
email: youfu.ok@163.com
language: zh-Hans
since: 2014
theme: next

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://youfu.xyz
root: /
permalink: :year/:month/:day/:title/

# Directory
source_dir: source
public_dir: public

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: localhost
logger: false
logger_format: dev


index_generator:
  per_page: 1

archive_generator:
  per_page: 0
  yearly: true
  monthly: true

tag_generator:
  per_page: 10

# Social links
social:
  GitHub: https://github.com/chenyoufu
  辉神博客: http://flyaway.me/

baidu_analytics: 79422e1e0a95c1774f227dadecc2ce8f
duoshuo_shortname: youfuxyz
creative_commons: by-nc-sa


plugins:
- hexo-generator-sitemap

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: git@github.com:chenyoufu/chenyoufu.github.io.git,master
    coding: git@git.coding.net:youfu/youfuNotes.git,coding-pages
