menu:
  首页: /
  存档: /archives
  关于: /about
  RSS: /atom.xml

widgets:
- search
- category
- archive
- tagcloud
- recent_posts
- blogroll
- recent_comments
- recent_visitors
- weibo


excerpt_link: 阅读全文

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:

fancybox: true

google_analytics:
rss: /atom.xml

# Duoshuo
duoshuo: youfuxyz 

# Baidu share
baidushare: true
